server:
  grpc:
    interface: 0.0.0.0
    port: 3200
  http:
    interface: 0.0.0.0
    port: 3201

database:
  host: 192.168.1.58
  port: 5432
  username: postgres
  password: postgres
  db: postgres